on:
  push:
    branches:
      - '*'
  pull_request:
    branches:
      - master
      - dev

name: R-CMD-check

jobs:
  R-CMD-check:
    runs-on: ${{ matrix.config.os }}

    name: ${{ matrix.config.os }} (${{ matrix.config.r }}) ${{ matrix.config.suffix }}

    strategy:
      fail-fast: false
      matrix:
        config:
# running Windows and Mac with --no-examples to avoid spurious Stan crashes in examples
          - {os: windows-latest, r: 'release', suffix: 'quick', not_cran: 'false', check_options: '"--no-build-vignettes", "--ignore-vignettes", "--no-examples"'}
          - {os: macOS-latest, r: 'release', suffix: 'quick', not_cran: 'false', check_options: '"--no-build-vignettes", "--ignore-vignettes", "--no-examples"'}
          - {os: ubuntu-latest, r: 'devel', suffix: '', not_cran: 'true', check_options: 'NULL', rspm: "https://packagemanager.rstudio.com/cran/__linux__/bionic/latest", http-user-agent: 'release'}
          - {os: ubuntu-latest, r: 'release', suffix: '', not_cran: 'true', check_options: 'NULL', rspm: "https://packagemanager.rstudio.com/cran/__linux__/bionic/latest"}
          - {os: ubuntu-latest, r: 'release', suffix: 'quick', not_cran: 'false', check_options: '"--no-build-vignettes", "--ignore-vignettes"', rspm: "https://packagemanager.rstudio.com/cran/__linux__/bionic/latest"}
          - {os: ubuntu-latest, r: 'oldrel', suffix: 'quick', not_cran: 'false', check_options: '"--no-build-vignettes", "--ignore-vignettes"', rspm: "https://packagemanager.rstudio.com/cran/__linux__/bionic/latest"}
          - {os: ubuntu-latest, r: '4.1', suffix: 'quick', not_cran: 'false', check_options: '"--no-build-vignettes", "--ignore-vignettes"', rspm: "https://packagemanager.rstudio.com/cran/__linux__/bionic/latest"}
          - {os: ubuntu-latest, r: '4.0', suffix: 'quick', not_cran: 'false', check_options: '"--no-build-vignettes", "--ignore-vignettes"', rspm: "https://packagemanager.rstudio.com/cran/__linux__/bionic/latest"}
          - {os: ubuntu-latest, r: '3.6', suffix: 'quick', not_cran: 'false', check_options: '"--no-build-vignettes", "--ignore-vignettes"', rspm: "https://packagemanager.rstudio.com/cran/__linux__/bionic/latest"}

    env:
      R_REMOTES_NO_ERRORS_FROM_WARNINGS: true
      GITHUB_PAT: ${{ secrets.GITHUB_TOKEN }}
      _R_CHECK_FORCE_SUGGESTS_: false

    steps:
      - uses: actions/checkout@v4

      - uses: r-lib/actions/setup-pandoc@v2

      - uses: r-lib/actions/setup-r@v2
        with:
          r-version: ${{ matrix.config.r }}
          http-user-agent: ${{ matrix.config.http-user-agent }}
          use-public-rspm: true

      - uses: r-lib/actions/setup-r-dependencies@v2
        with:
          extra-packages: |
            any::rcmdcheck
            any::BH
            any::RcppEigen
            Matrix
            emmeans=?ignore-before-r=4.3.0
          needs: check

#      - name: Install system dependencies
#        if: runner.os == 'Linux'
#        env:
#          RHUB_PLATFORM: linux-x86_64-ubuntu-gcc
#        run: |
#          Rscript -e "remotes::install_github('r-hub/sysreqs')"
#          sysreqs=$(Rscript -e "cat(sysreqs::sysreq_commands('DESCRIPTION'))")
#          sudo -s eval "$sysreqs"
#          sudo apt-get install jags cargo libudunits2-dev libgdal-dev
# cargo: for gifski
# libudunits2-dev   for units (transformr)
# libgdal-dev       for sf (transformr)

      - name: Check
        env:
          _R_CHECK_CRAN_INCOMING_REMOTE_: false
          NOT_CRAN: ${{ matrix.config.not_cran }}
        run: rcmdcheck::rcmdcheck(args = c("--no-manual", "--as-cran", ${{ matrix.config.check_options }}), error_on = "warning", check_dir = "check")
        shell: Rscript {0}

      - name: Upload check results
        if: failure()
        uses: actions/upload-artifact@v3
        with:
          name: ${{ runner.os }}-r${{ matrix.config.r }}-results
          path: check

      - name: Test coverage
        if: matrix.config.r == 'release' && runner.os == 'Linux' && matrix.config.suffix == 'quick'
        run: covr::codecov()
        shell: Rscript {0}
